name: Feature
description: Add or improve a feature
labels: ["type:feature"]
body:
  - type: textarea
    id: background
    attributes: { label: Background / Why }
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Given/When/Then; API contract; UI states
  - type: textarea
    id: qa
    attributes:
      label: QA Notes
      description: test data / curl / screenshots

